"""Changed columns struct.

Revision ID: 6781b33f7a4c
Revises: 32749123433f
Create Date: 2023-11-16 14:29:33.159936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6781b33f7a4c'
down_revision = '32749123433f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cylinder', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('speedMax', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('urlImage', sa.Text(), nullable=False))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speedMax', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('power', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('power')
        batch_op.drop_column('speedMax')

    with op.batch_alter_table('motorcycles', schema=None) as batch_op:
        batch_op.drop_column('urlImage')
        batch_op.drop_column('price')
        batch_op.drop_column('stock')
        batch_op.drop_column('speedMax')
        batch_op.drop_column('cylinder')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
