"""Changes on user

Revision ID: e10914efe4b9
Revises: f8b4c00c2e89
Create Date: 2023-11-24 22:00:12.718716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10914efe4b9'
down_revision = 'f8b4c00c2e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_employee',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_employee',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
