"""Load models

Revision ID: e50d2e0432d6
Revises: 
Create Date: 2023-11-10 22:51:40.426381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50d2e0432d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vehicles')
    op.drop_table('Motorcycles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Motorcycles',

    )
    op.create_table('Vehicles',

    )
    # ### end Alembic commands ###
