"""Addded new attribute

Revision ID: f8b4c00c2e89
Revises: bae13f127617
Create Date: 2023-11-24 21:44:32.498987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b4c00c2e89'
down_revision = 'bae13f127617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_employee',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_employee',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
